### ISSUE TITLE
python manage.py collecttemplates fails with error IndexError: list index out of range

### ISSUE THREAD

**Issue by softinio** [stephenmcd/mezzanine#1512]
When Using: 

- Python 3.5
- Django 1.9.1
- Mezzanine 4.1

This management command fails:

    python manage.py collecttemplates

Error message: 
    
```
/usr/local/lib/python3.5/site-packages/django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  RemovedInDjango110Warning)

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/mezzanine/core/management/commands/collecttemplates.py", line 42, in handle
    to_dir = settings.TEMPLATE_DIRS[0]
IndexError: list index out of range
```

**Comment by stephenmcd** [comment]
Thanks for the report.

**Comment by maxrozen-codesource** [comment]
Just confirming this is issue also occurs with:
Python 2.7.6
Django 1.9.1
Mezzanine 4.1

**Comment by satriani04** [comment]
i have same error too..
help me...

**Comment by rozenmd** [comment]
Go to mezzanine/core/management/commands/collecttemplates.py

Edit line 42, make it say
to_dir = settings.TEMPLATES[0]["DIRS"][0]

**Comment by satriani04** [comment]
it still give an error 
![py](https://cloud.githubusercontent.com/assets/8855315/12575299/0665820a-c43e-11e5-87ef-577dac2eb55a.PNG)

**Comment by slav0nic** [comment]
@satriani04 looks like you have problem with mixing tab/space in file

**Comment by dmitrymar** [comment]
I got the same error as @softinio At first I followed @rozenmd advice which worked but I decided to just downgrade for now until official fix is available. 
```pip install Mezzanine==4.0.1```

**Comment by albenik** [comment]
Simply workaround without installed Mezzanine patching
Just temporary add line `TEMPLATE_DIRS = [TEMPLATES[0]['DIRS'][0]]` to `settings.py` file execute `collect_templates` command and remove added line after it.
Profit!

**Comment by satriani04** [comment]
ok it fixed now. thanks all..

**Comment by mateuo** [comment]
Thank you albenik

**Comment by beckastar** [comment]
"Just temporary add line TEMPLATE_DIRS = [TEMPLATES[0]['DIRS'][0]] to settings.py file execute collect_templates command and remove added line after it."

Remove which line? Sorry, I don't understand.

**Comment by mateuo** [comment]
the line you have just added.
regards

**Comment by donnydavis** [comment]
This still is not fixed. I'm on the latest and the posted fix above doesn't work either

**Comment by nicholaskajoh** [comment]
This bug is not still fixed. I'm on version 4.1.0 and I'm still getting the error. Though the temporary fix by    @albenik worked just fine. Let me mention that the line `TEMPLATE_DIRS = [TEMPLATES[0]['DIRS'][0]]` should be under the `TEMPLATES` array. It's obvious, but when you're angry and frustrated at the same time, you could make such a silly mistake, like I did.

**Comment by jerivas** [comment]
It is fixed in the master branch, not 4.1.0. The fix will be part of the 
next Mezzanine release.

**Comment by ramitsurana** [comment]
Here is pic how to configure it 
![mezzaninequickfix](https://cloud.githubusercontent.com/assets/8342133/17049570/bbab57c6-500b-11e6-9b20-0e5adfe4ba25.png)

Here's my output 
![mezzanine](https://cloud.githubusercontent.com/assets/8342133/17049624/16e78290-500c-11e6-9684-38b19703c111.png)
