### ISSUE TITLE
Non-Django fields break field injection

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/mezzanine#1513]
This is with Mezzanine 4.1 and Django 1.9.

First, I tried to inject a non-built-in field (like one of Mezzanine's):
```python
EXTRA_MODEL_FIELDS = (
    (
        "mezzanine.pages.models.Page.featured_image",
        "mezzanine.core.fields.FileField",
        ("Featured Image",),
        {"format": "Image", "blank": True,
         "upload_to": "pages/featured-images",
         "help_text": "Image displayed at the top of this page"},
    ),
)
```
Then, I tried to create the migration: `python manage.py makemigrations pages`
I got this traceback:
```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/boot/__init__.py", line 82, in <module>
    fields = parse_extra_model_fields(getattr(settings, "EXTRA_MODEL_FIELDS", []))
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/boot/__init__.py", line 70, in parse_extra_model_fields
    field_class = import_field(entry[1])
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/boot/__init__.py", line 53, in import_field
    return import_dotted_path(fully_qualified)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/utils/importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/core/fields.py", line 127, in <module>
    settings.PACKAGE_NAME_FILEBROWSER)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/utils/importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/filebrowser_safe/fields.py", line 17, in <module>
    from filebrowser_safe.base import FileObject
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/filebrowser_safe/base.py", line 22, in <module>
    from filebrowser_safe.functions import get_file_type, path_strip, get_directory
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/filebrowser_safe/functions.py", line 16, in <module>
    from django.contrib.sites.models import Site
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 83, in <module>
    class Site(models.Model):
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
Importing one of Django's own fields, like `IntegerField` does not cause the error.

**Comment by egut** [comment]
I can confirm this bug, was looking for a solution for it. The same EXTRA_MODEL_FIELDS works fine in mezzenine 4.0.1

**Comment by jerivas** [comment]
So, rolling back to Django 1.8.8 makes the error go away. However, if you start a new database (Postgres in my case), you will encounter an error when applying the migration that injects the new field (`featured_image`). Not sure if this is a separate issue, but here is the traceback (this is from `createdb`):

```
Applying pages.0004_page_featured_image...Traceback (most recent call last):
File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/mezzanine/core/management/commands/createdb.py", line 60, in handle
    interactive=self.interactive)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 398, in add_field
    self.execute(sql, params)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jerivas/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "featured_image" of relation "pages_page" already exists
```
Commenting-out `EXTRA_MODEL_FIELDS` during the application of migrations seems to be the solution.

**Comment by dszmaj** [comment]
I confirm the error, the following breaks createdb method of manage.py, says that slider field is doubled

'''python
EXTRA_MODEL_FIELDS = (
    (
        # Dotted path to field.
        "mezzanine.pages.models.RichTextPage.slider",
        # Dotted path to field class.
        "BooleanField",
        # Positional args for field class.
        (_("Czy główny slider ma być widoczny?"),),
        # Keyword args for field class.
        {'default': False},
    ),
)
'''

**Comment by encolpe** [comment]
Is there a plan to work on this bug?

**Comment by stephenmcd** [comment]
@encolpe presumably nothing has happened since nothing is mentioned

If this is affecting you, perhaps could you take a look at it.

Thanks!

**Comment by Cajoline** [comment]
I have the same issue with Django 1.9 and Mezzanine 4.1

**Comment by AlexHill** [comment]
I don't know what changed to make this not work, but it's caused by models being imported as a side-effect of importing the specified field. For `FileField`, fortunately the problematic import was unused, so it's a very easy fix: 70eeef9.

@jerivas can you try that and see if it solves your problem?

I strongly suspect sanitising field definitions by removing all module-level model imports will fix this.

**Comment by jerivas** [comment]
Thanks Alex. I'll hopefully have some spare time to test it out later this week.

**Comment by AlexHill** [comment]
@jerivas the model import issue only addresses the first issue posted. That solves the migrations issue under Django 1.9 for me. @Cajoline, @dszmaj, @encolpe, @egut, can you let us know exactly what fields you're trying to inject, and what versions of Django and Mezzanine you're running (if you haven't posted them already)? Also, your traceback will either end with `django.db.utils.ProgrammingError: column "<column>" of relation "<table>" already exists` or `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.` – can you let us know which?

I can confirm the "duplicate field" issue still exists running under 1.8, on SQLite as well, and with any kind of field including built-ins.

Given the same setup you've described above, the crash occurs for me while applying the **first** migration of the pages app, whereas yours occurs while applying just the new one. Can you confirm the previous three migrations applied OK for you against an empty database? What if you try with SQLite?

**Comment by Cajoline** [comment]
@AlexHill I have this error
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet

I will try with empty database and sqlite 

Thx

**Comment by AlexHill** [comment]
@Cajoline what field class are you trying to inject?

**Comment by Cajoline** [comment]
@AlexHill I try to inject RichTextField

**Comment by AlexHill** [comment]
Interesting. `RichTextField` works for me, either starting with an empty database and using `createdb`, or running `migrate` after adding the field to an existing project. Can you post your full stack trace please?

**Comment by Cajoline** [comment]
Hi @AlexHill 

My full stack trace here:

`/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/mezzanine/utils/conf.py:47: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/mezzanine/utils/conf.py:47: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fa6f4bd0158>
Traceback (most recent call last):
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/mezzanine/boot/__init__.py", line 77, in <module>
    fields = parse_extra_model_fields(getattr(settings, "EXTRA_MODEL_FIELDS", []))
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/mezzanine/boot/__init__.py", line 65, in parse_extra_model_fields
    field_class = import_field(entry[1])
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/mezzanine/boot/__init__.py", line 48, in import_field
    return import_dotted_path(fully_qualified)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/mezzanine/utils/importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/mezzanine/core/fields.py", line 127, in <module>
    settings.PACKAGE_NAME_FILEBROWSER)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/mezzanine/utils/importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/filebrowser_safe/fields.py", line 17, in <module>
    from filebrowser_safe.base import FileObject
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/filebrowser_safe/base.py", line 22, in <module>
    from filebrowser_safe.functions import get_file_type, path_strip, get_directory
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/filebrowser_safe/functions.py", line 16, in <module>
    from django.contrib.sites.models import Site
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/contrib/sites/models.py", line 83, in <module>
    class Site(models.Model):
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

Thank you !

**Comment by ryneeverett** [comment]
@Cajoline Does stephenmcd/filebrowser-safe/pull/75 fix that?

**Comment by Cajoline** [comment]
@ryneeverett Thx you, i will try it !

**Comment by AlexHill** [comment]
Ok yeah. I still had the filebrowser change applied, which was why I wasn't getting the error. Importing `RichTextField` triggers the import of the filebrowser-safe fields, which triggers the import of `Site` as above. The `filebrowser-safe` patch should fix it.

**Comment by stephenmcd** [comment]
I still get the same traceback in https://github.com/stephenmcd/mezzanine/issues/1513#issuecomment-219721970 with https://github.com/stephenmcd/filebrowser-safe/pull/75 applied.

**Comment by ryneeverett** [comment]
@stephenmcd Your traceback must be somewhat different since this that PR removes this line:

```
  File "/home/cajoline/.virtualenvs/siat/lib/python3.4/site-packages/filebrowser_safe/functions.py", line 16, in <module>
    from django.contrib.sites.models import Site
```

**Comment by stephenmcd** [comment]
@ryneeverett sorry I think I got https://github.com/stephenmcd/filebrowser-safe/pull/75 and https://github.com/stephenmcd/filebrowser-safe/pull/70 mixed up, but either way, I meant I get the same exception (`AppRegistryNotReady`), not a line for line identical traceback. Here's mine:

`
Traceback (most recent call last):
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/stephenmcd/dev/mezzanine/mezzanine/boot/__init__.py", line 77, in <module>
    fields = parse_extra_model_fields(getattr(settings, "EXTRA_MODEL_FIELDS", []))
  File "/Users/stephenmcd/dev/mezzanine/mezzanine/boot/__init__.py", line 65, in parse_extra_model_fields
    field_class = import_field(entry[1])
  File "/Users/stephenmcd/dev/mezzanine/mezzanine/boot/__init__.py", line 48, in import_field
    return import_dotted_path(fully_qualified)
  File "/Users/stephenmcd/dev/mezzanine/mezzanine/utils/importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/stephenmcd/dev/mezzanine/mezzanine/core/fields.py", line 127, in <module>
    settings.PACKAGE_NAME_FILEBROWSER)
  File "/Users/stephenmcd/dev/mezzanine/mezzanine/utils/importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/stephenmcd/dev/filebrowser-safe/filebrowser_safe/fields.py", line 17, in <module>
    from filebrowser_safe.base import FileObject
  File "/Users/stephenmcd/dev/filebrowser-safe/filebrowser_safe/base.py", line 22, in <module>
    from filebrowser_safe.functions import get_file_type, path_strip, get_directory
  File "/Users/stephenmcd/dev/filebrowser-safe/filebrowser_safe/functions.py", line 13, in <module>
    from django.contrib.sites.models import Site
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/contrib/sites/models.py", line 83, in <module>
    class Site(models.Model):
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/stephenmcd/dev/env/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet`

**Comment by ryneeverett** [comment]
@stephenmcd You still have the offending line that stephenmcd/filebrowser-safe#75 removes in your traceback:

```
  File "/Users/stephenmcd/dev/filebrowser-safe/filebrowser_safe/functions.py", line 13, in <module>
    from django.contrib.sites.models import Site
```

I had removed that line in stephenmcd/filebrowser-safe#70 so when it was reverted that line got added back.

**Comment by stephenmcd** [comment]
@ryneeverett thanks for spotting that :-) I fixed it in https://github.com/stephenmcd/filebrowser-safe/commit/5cf60430e4c54181e6608ee726e71c3547754c02 and `EXTRA_MODEL_FIELDS` works now.

**Comment by widder** [comment]
Same error in Django 1.10 and Mezzanine 4.4.2

```
    (
        # Dotted path to field.
        "mezzanine.blog.models.BlogPost.extra_content",
        # Dotted path to field class.
        "mezzanine.core.fields.RichTextField",
        # Positional args for field class.
        ("Extra content",),
        # Keyword args for field class.
        {"blank": True, "max_length": 2000},
    ),
``` 


```
 $./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/mezzanine/boot/__init__.py", line 77, in <module>
    fields = parse_extra_model_fields(getattr(settings, "EXTRA_MODEL_FIELDS", []))
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/mezzanine/boot/__init__.py", line 65, in parse_extra_model_fields
    field_class = import_field(entry[1])
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/mezzanine/boot/__init__.py", line 48, in import_field
    return import_dotted_path(fully_qualified)
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/mezzanine/utils/importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/mezzanine/core/fields.py", line 103, in <module>
    settings.PACKAGE_NAME_FILEBROWSER)
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/mezzanine/utils/importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/widder/PycharmProjects/projectroot/filebrowser_safe/fields.py", line 17, in <module>
    from filebrowser_safe.settings import *
  File "/Users/widder/PycharmProjects/projectroot/filebrowser_safe/settings.py", line 13, in <module>
    import tinymce.settings
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/tinymce/settings.py", line 19, in <module>
    JS_ROOT = getattr(settings, 'TINYMCE_JS_ROOT', finders.find('tiny_mce', all=False))
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/contrib/staticfiles/finders.py", line 249, in find
    for finder in get_finders():
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/contrib/staticfiles/finders.py", line 264, in get_finders
    yield get_finder(finder_path)
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/contrib/staticfiles/finders.py", line 277, in get_finder
    return Finder()
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/contrib/staticfiles/finders.py", line 129, in __init__
    app_configs = apps.get_app_configs()
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/Users/widder/PycharmProjects/venvs/myapp/lib/python3.5/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
